package top.r3944realms.lendandregret.contents;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import top.r3944realms.lendandregret.LendAndRegret;

public class LARCreativeModeTab {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, LendAndRegret.MOD_ID);

    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> MAIN_TAB = CREATIVE_MODE_TABS.register("main",
            () -> CreativeModeTab.builder()
                    .title(Component.translatable("itemGroup.lendandregret"))
                    .icon(() -> LARItems.ICON_ITEM.get().getDefaultInstance())
                    .displayItems((params, output) -> {
                        output.accept(LARItems.ICON_ITEM.get());
                    })
                    .build());
}
